language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - php: 7.4snapshot

cache:
  directories:
    - $COMPOSER_CACHE_DIR

install:
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - mkdir -p build/logs
  - ./bin/phpunit --coverage-clover build/logs/clover.xml
  - ./bin/phpcs --standard=php_cs.xml src tests

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
